name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 2375:2375
        env:
          DOCKER_TLS_CERTDIR: ''
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t larsmagnusgithub/react-test -f ./client/Dockerfile.dev ./client

      - name: Run tests
        run: docker run -e CI=true larsmagnusgithub/react-test npm test