name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image for testing
        run: docker build -t larsmagnusgithub/react-test -f ./client/Dockerfile.dev ./client

      - name: Run tests
        run: docker run -e CI=true larsmagnusgithub/react-test npm test -- --coverage

  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Docker
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build multi-client image
        run: docker build -t larsmagnusgithub/multi-client ./client

      - name: Build multi-nginx image
        run: docker build -t larsmagnusgithub/multi-nginx ./nginx

      - name: Build multi-server image
        run: docker build -t larsmagnusgithub/multi-server ./server

      - name: Build multi-worker image
        run: docker build -t larsmagnusgithub/multi-worker ./worker

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_ID }}" --password-stdin
        env:
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push multi-client image
        run: docker push larsmagnusgithub/multi-client

      - name: Push multi-nginx image
        run: docker push larsmagnusgithub/multi-nginx

      - name: Push multi-server image
        run: docker push larsmagnusgithub/multi-server

      - name: Push multi-worker image
        run: docker push larsmagnusgithub/multi-worker
